#if [ -z "$1" ] ; then
#echo Input Password is missing
#exit
#fi
#
#
#source common.sh
#component=shipping
#MAVEN
#
#dnf install mysql -y
#for file in schema app-user master-data ; do
#mysql -h mysql-dev.gdevops65.shop -uroot -p$1 < /app/db/$file.sql
#done


- name: Load Maven
  ansible.builtin.import_role:
    name: common
    tasks_from: maven

- name: Install Mysql client
  ansible.builtin.dnf:
    name: mysql
    state: installed

- name: Load Schema
  ansible.builtin.shell: mysql -h mysql-dev.gdevops65.shop -uroot -pRoboShop@1 < /app/db/schema.sql

- name: Load user
  ansible.builtin.shell: mysql -h mysql-dev.gdevops65.shop -uroot -pRoboShop@1 < /app/db/app-user.sql

- name: Load Master-Data
  ansible.builtin.shell: mysql -h mysql-dev.gdevops65.shop -uroot -pRoboShop@1 < /app/db/master-data.sql



