#dnf install mysql-server -y
#systemctl enable mysqld
#systemctl start mysqld
#mysql_secure_installation --set-root-pass $1


- name: Install Mysql
  ansible.builtin.dnf:
    name: mysql.server
    state: installed

- name: Start MySql
  ansible.builtin.systemd_service:
    name: mysql
    state: restarted
    enabled: yes

- name: Set Root Password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1
