- name: Load NodeJs
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs


#- name: Install MongoDb- Mongosh
#  ansible.builtin.unarchive:
#    name: mongodb-mongosh



#  source common.sh
#  component=catalogue
#  NODEJS
#
#  dnf install mongodb-mongosh -y
#  mongosh --host  mongodb-dev.gdevops65.shop </app/db/master-data.js