#    NODEJS() {
#    dnf module disable nodejs -y
#    dnf module enable nodejs:20 -y
#    dnf install nodejs -y
#    cp ${component}.service /etc/systemd/system/${component}.service
#
#    APP_PREREQ
#
#    npm install
#
#    SYSTEMD
#  }


- name: Disable default Nodejs and enable nodejs 20
  ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:20 -y


- name: Install Nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: installed

- name: Load App Pre-Req
  ansible.builtin.import_role:
    name: common
    tasks_from: app prereq

- name: Install Nodejs Dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app


- name: Load systemd service
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd
